#!/usr/bin/env python3
"""
Create GitHub Issues from Multi-Agent Review Findings

This script reads the multi-agent review report and creates GitHub issues
for actionable findings (medium and low severity).

Supports multiple methods:
1. GitHub CLI (gh) - if available
2. GitHub REST API - if GITHUB_TOKEN is set
3. Markdown files - as fallback for manual creation
"""

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Any, Optional
import urllib.request
import urllib.error


class IssueCreator:
    """Creates GitHub issues from review findings."""

    def __init__(self, report_file: Path, repo_owner: Optional[str] = None, repo_name: Optional[str] = None):
        self.report_file = report_file
        self.report_data = self._load_report()
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        self.github_token = os.environ.get("GITHUB_TOKEN")

        # Determine creation method
        self.use_gh_cli = self._check_gh_cli()
        self.use_api = bool(self.github_token and repo_owner and repo_name)
        self.use_markdown = not (self.use_gh_cli or self.use_api)

        # Map categories to GitHub labels
        self.category_to_labels = {
            "Authentication": ["security", "enhancement"],
            "Async Patterns": ["code-quality", "refactoring"],
            "Code Complexity": ["code-quality", "refactoring", "enhancement"],
            "Dependencies": ["dependencies", "enhancement"],
            "XML Security": ["security"],
            "Input Validation": ["security"],
            "Performance": ["performance", "enhancement"],
            "Architecture": ["architecture", "enhancement"],
            "Testing": ["testing", "enhancement"],
            "Documentation": ["documentation", "enhancement"]
        }

        # Map severity to priority labels
        self.severity_to_labels = {
            "critical": ["priority: critical", "bug"],
            "high": ["priority: high", "bug"],
            "medium": ["priority: medium", "enhancement"],
            "low": ["priority: low", "enhancement"],
            "info": []
        }

    def _check_gh_cli(self) -> bool:
        """Check if GitHub CLI is available."""
        try:
            subprocess.run(
                ["gh", "--version"],
                capture_output=True,
                check=True
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    def _load_report(self) -> Dict[str, Any]:
        """Load the review report from JSON file."""
        with open(self.report_file, 'r') as f:
            return json.load(f)

    def _get_labels(self, category: str, severity: str) -> List[str]:
        """Get appropriate labels for a finding."""
        labels = set()

        # Add category-based labels
        if category in self.category_to_labels:
            labels.update(self.category_to_labels[category])

        # Add severity-based labels
        if severity in self.severity_to_labels:
            labels.update(self.severity_to_labels[severity])

        # Add source label
        labels.add("multi-agent-review")

        return list(labels)

    def _create_issue_body(self, finding: Dict[str, Any], severity: str) -> str:
        """Create formatted issue body."""
        body_parts = [
            "## Description",
            "",
            finding["description"],
            "",
            "## Category",
            "",
            f"**{finding['category']}** (Severity: `{severity}`)",
            ""
        ]

        # Add file location if available
        if finding.get("file_path"):
            file_path = finding["file_path"].replace("/home/user/luxorliving/", "")
            body_parts.extend([
                "## Affected File",
                "",
                f"`{file_path}`",
                ""
            ])

        # Add recommendation if available
        if finding.get("recommendation"):
            body_parts.extend([
                "## Recommendation",
                "",
                finding["recommendation"],
                ""
            ])

        # Add metadata
        body_parts.extend([
            "---",
            "",
            "_This issue was automatically generated by the Multi-Agent Code Review System._",
            f"_Report timestamp: {self.report_data['timestamp']}_"
        ])

        return "\n".join(body_parts)

    def _create_github_issue_cli(self, title: str, body: str, labels: List[str]) -> bool:
        """Create a GitHub issue using gh CLI."""
        try:
            # Build the gh issue create command
            cmd = [
                "gh", "issue", "create",
                "--title", title,
                "--body", body
            ]

            # Add labels
            if labels:
                cmd.extend(["--label", ",".join(labels)])

            # Execute command
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )

            issue_url = result.stdout.strip()
            print(f"✅ Created issue: {issue_url}")
            return True

        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to create issue '{title}'")
            print(f"   Error: {e.stderr}")
            return False
        except Exception as e:
            print(f"❌ Unexpected error creating issue '{title}': {e}")
            return False

    def _create_github_issue_api(self, title: str, body: str, labels: List[str]) -> bool:
        """Create a GitHub issue using REST API."""
        try:
            url = f"https://api.github.com/repos/{self.repo_owner}/{self.repo_name}/issues"

            data = {
                "title": title,
                "body": body,
                "labels": labels
            }

            headers = {
                "Authorization": f"token {self.github_token}",
                "Accept": "application/vnd.github.v3+json",
                "Content-Type": "application/json"
            }

            req = urllib.request.Request(
                url,
                data=json.dumps(data).encode('utf-8'),
                headers=headers,
                method='POST'
            )

            with urllib.request.urlopen(req) as response:
                result = json.loads(response.read().decode('utf-8'))
                issue_url = result.get('html_url', 'Unknown URL')
                print(f"✅ Created issue: {issue_url}")
                return True

        except urllib.error.HTTPError as e:
            error_body = e.read().decode('utf-8')
            print(f"❌ HTTP Error creating issue '{title}'")
            print(f"   Status: {e.code}")
            print(f"   Error: {error_body}")
            return False
        except Exception as e:
            print(f"❌ Unexpected error creating issue '{title}': {e}")
            return False

    def _save_issue_markdown(self, title: str, body: str, labels: List[str], index: int) -> bool:
        """Save issue as markdown file for manual creation."""
        try:
            # Create issues directory
            issues_dir = Path.cwd() / "review_issues"
            issues_dir.mkdir(exist_ok=True)

            # Sanitize filename
            filename = f"{index:02d}_{title.replace('[', '').replace(']', '').replace('/', '_')[:50]}.md"
            filepath = issues_dir / filename

            # Create markdown content
            content = [
                f"# {title}",
                "",
                f"**Labels:** {', '.join(labels)}",
                "",
                "---",
                "",
                body
            ]

            with open(filepath, 'w') as f:
                f.write('\n'.join(content))

            print(f"📄 Saved to: {filepath}")
            return True

        except Exception as e:
            print(f"❌ Failed to save markdown for '{title}': {e}")
            return False

    def _create_github_issue(self, title: str, body: str, labels: List[str], index: int = 0) -> bool:
        """Create a GitHub issue using the appropriate method."""
        if self.use_gh_cli:
            return self._create_github_issue_cli(title, body, labels)
        elif self.use_api:
            return self._create_github_issue_api(title, body, labels)
        else:
            return self._save_issue_markdown(title, body, labels, index)

    def create_issues_for_findings(self, severities: List[str] = None) -> Dict[str, int]:
        """Create GitHub issues for findings of specified severities."""
        if severities is None:
            severities = ["medium", "low"]

        stats = {
            "total": 0,
            "created": 0,
            "failed": 0
        }

        print(f"\n🚀 Creating GitHub issues from multi-agent review findings")
        print(f"📊 Severities: {', '.join(severities)}")

        # Print method being used
        if self.use_gh_cli:
            print(f"🔧 Method: GitHub CLI (gh)\n")
        elif self.use_api:
            print(f"🔧 Method: GitHub REST API\n")
        else:
            print(f"🔧 Method: Markdown files (manual creation required)\n")
            print(f"💡 Issues will be saved to ./review_issues/ directory\n")

        issue_index = 0
        for severity in severities:
            findings = self.report_data["findings_by_severity"].get(severity, [])

            if not findings:
                print(f"ℹ️  No {severity} severity findings to process\n")
                continue

            print(f"\n{'='*80}")
            print(f"Processing {severity.upper()} severity findings ({len(findings)} total)")
            print('='*80 + "\n")

            for i, finding in enumerate(findings, 1):
                issue_index += 1
                stats["total"] += 1

                # Create issue title
                title = f"[{severity.upper()}] {finding['title']}"

                # Create issue body
                body = self._create_issue_body(finding, severity)

                # Get labels
                labels = self._get_labels(finding["category"], severity)

                print(f"{i}. Creating issue: {finding['title']}")
                print(f"   Labels: {', '.join(labels)}")

                # Create the issue
                if self._create_github_issue(title, body, labels, issue_index):
                    stats["created"] += 1
                else:
                    stats["failed"] += 1

                print()

        return stats

    def print_summary(self, stats: Dict[str, int]) -> None:
        """Print summary of issue creation."""
        print("\n" + "="*80)
        print("📊 ISSUE CREATION SUMMARY")
        print("="*80)
        print(f"\n✅ Successfully created: {stats['created']}")
        print(f"❌ Failed: {stats['failed']}")
        print(f"📈 Total processed: {stats['total']}\n")


def main():
    """Main entry point."""
    # Determine repository path
    repo_path = Path.cwd()
    report_file = repo_path / "multi_agent_review_report.json"

    # Check if report file exists
    if not report_file.exists():
        print(f"❌ Error: Report file not found: {report_file}")
        print("   Please run multi_agent_review.py first to generate the report.")
        sys.exit(1)

    # Try to determine repo owner and name from git
    repo_owner = None
    repo_name = None
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            check=True
        )
        remote_url = result.stdout.strip()
        # Parse GitHub URL (supports both HTTPS and SSH)
        if "github.com" in remote_url:
            parts = remote_url.replace("git@github.com:", "").replace("https://github.com/", "").replace(".git", "").split("/")
            if len(parts) >= 2:
                repo_owner = parts[-2]
                repo_name = parts[-1]
    except:
        pass

    # Create issue creator
    creator = IssueCreator(report_file, repo_owner=repo_owner, repo_name=repo_name)

    # Print configuration
    print("\n" + "="*80)
    print("⚙️  CONFIGURATION")
    print("="*80)
    print(f"Repository: {repo_owner}/{repo_name}" if repo_owner and repo_name else "Repository: Unable to detect")
    print(f"GitHub CLI available: {'Yes' if creator.use_gh_cli else 'No'}")
    print(f"GitHub Token available: {'Yes' if creator.github_token else 'No'}")
    print(f"Creation method: ", end="")
    if creator.use_gh_cli:
        print("GitHub CLI")
    elif creator.use_api:
        print("GitHub REST API")
    else:
        print("Markdown files (manual)")

    # Create issues for medium and low severity findings
    # Skip info findings as they are positive observations
    stats = creator.create_issues_for_findings(severities=["medium", "low"])

    # Print summary
    creator.print_summary(stats)

    # Additional info for markdown method
    if creator.use_markdown:
        print("\n💡 To create issues from markdown files:")
        print("   1. Review files in ./review_issues/ directory")
        print("   2. Create issues manually on GitHub")
        print("   3. Or install GitHub CLI: https://cli.github.com/\n")

    return 0 if stats["failed"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
