#!/bin/bash
#
# Create GitHub Issues from Markdown Files
#
# This script reads the markdown files generated by create_issues_from_review.py
# and creates GitHub issues using the GitHub CLI (gh).
#
# Prerequisites:
# - GitHub CLI (gh) installed and authenticated
# - Run: gh auth login
#
# Usage:
#   ./create_github_issues.sh
#

set -e

REPO="phismith91/luxorliving"
ISSUES_DIR="review_issues"

# Check if gh is installed
if ! command -v gh &> /dev/null; then
    echo "❌ Error: GitHub CLI (gh) is not installed"
    echo ""
    echo "Install it from: https://cli.github.com/"
    echo ""
    echo "On Ubuntu/Debian:"
    echo "  sudo apt install gh"
    echo ""
    echo "On macOS:"
    echo "  brew install gh"
    echo ""
    echo "After installation, authenticate with:"
    echo "  gh auth login"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ Error: Not authenticated with GitHub"
    echo ""
    echo "Please authenticate with:"
    echo "  gh auth login"
    exit 1
fi

# Check if issues directory exists
if [ ! -d "$ISSUES_DIR" ]; then
    echo "❌ Error: Issues directory not found: $ISSUES_DIR"
    echo ""
    echo "Please run create_issues_from_review.py first to generate the issue files."
    exit 1
fi

echo "================================================================================
🚀 Creating GitHub Issues
================================================================================
"
echo "Repository: $REPO"
echo "Issues directory: $ISSUES_DIR"
echo ""

# Counter
total=0
created=0
failed=0

# Process each markdown file
for file in "$ISSUES_DIR"/*.md; do
    if [ ! -f "$file" ]; then
        continue
    fi

    total=$((total + 1))
    filename=$(basename "$file")

    echo "Processing: $filename"

    # Extract title (first line without #)
    title=$(head -n 1 "$file" | sed 's/^# //')

    # Extract labels (line with **Labels:**)
    labels=$(grep "^\*\*Labels:\*\*" "$file" | sed 's/^\*\*Labels:\*\* //' | tr ',' '\n' | sed 's/^ *//' | tr '\n' ',' | sed 's/,$//')

    # Extract body (everything after the --- separator)
    body=$(awk '/^---$/,0' "$file" | tail -n +3)

    # Create the issue
    if gh issue create \
        --repo "$REPO" \
        --title "$title" \
        --body "$body" \
        --label "$labels" > /dev/null 2>&1; then
        created=$((created + 1))
        echo "  ✅ Created successfully"
    else
        failed=$((failed + 1))
        echo "  ❌ Failed to create"
    fi

    echo ""
done

echo "================================================================================
📊 SUMMARY
================================================================================
"
echo "✅ Successfully created: $created"
echo "❌ Failed: $failed"
echo "📈 Total processed: $total"
echo ""

if [ $failed -eq 0 ]; then
    echo "🎉 All issues created successfully!"
    exit 0
else
    echo "⚠️  Some issues failed to create. Please check the errors above."
    exit 1
fi
